### PR TITLE
Add working basic example in python

### PR DESCRIPTION
**Pull request by DanielSank**
Note that this branch was rebased on snail 31 Jan 2016 14:38. If anyone has this checked out elsewhere I recommend deleting the local branch and re-checking out.

@bemeurer

### CODE REVIEW

**Comment by DanielSank** [comment]
To try the example, first run `calculator.py` to start the calculator service. Then run `client.py` which will send one request to the calculator.

Also, I just realized that I modified a Scala file here. That was an accident, but it's not a big deal since the Scala stuff doesn't work yet anyway.

**Comment by lovesegfault** [comment]
I'll test this out tomorrow morning.

**Comment by lovesegfault** [comment]
Got a crash

``` python
espaco@Arch ~/C/cappy> python python/calculator.py 
Serving on ('127.0.0.1', 8083)
New connection accepted from 127.0.0.1 57914
Received data: b'{"args": [4], "id": 1, "method": "square"}'
Traceback (most recent call last):
  File "python/calculator.py", line 23, in <module>
    main()
  File "python/calculator.py", line 19, in main
    reactor.run()
  File "/home/espaco/Codes/cappy/python/network.py", line 30, in run
    self.do_select_iteration()
  File "/home/espaco/Codes/cappy/python/network.py", line 60, in do_select_iteration
    self.m[r].handle_read()
  File "/home/espaco/Codes/cappy/python/network.py", line 185, in handle_read
    self.protocol.data_received(data)
  File "/home/espaco/Codes/cappy/python/protocol.py", line 92, in data_received
    messages = self.stream.receive(data)
  File "/home/espaco/Codes/cappy/python/protocol.py", line 41, in receive
    completed = self.buf + data[start_index: i+1]
TypeError: Can't convert 'bytes' object to str implicitly
```

screenshot_20160204_102015

**Comment by lovesegfault** [comment]
Works with python2 though. Should I make it all Python 3 or leave it to Python 2? I always prefer 3, but I'm up to using whichever you prefer.

**Comment by DanielSank** [comment]
If you can make the wire data handling work right in both, then go for it.

**Comment by lovesegfault** [comment]
Alright. This looks good to me; let's merge it and then I'll start working on Python 3 support.

**Pull request merged**
